---
title: "Rhode Island Traffic Stops"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical-layout: fill
    css: style.css
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(RColorBrewer)

# Load data in 'global' chunk so it can be shared by all users of the dashboard
stops <- read.csv("data/police_project.csv")

# Drop the County name
stops$county_name <- NULL

# Remove redundant birth year column
stops$driver_age_raw <- NULL

# Drop the complex categorical columns
stops$violation_raw <- NULL
stops$search_type <- NULL

# Drop all rows (~5000) with missing values
stops <- na.omit(stops)

# Convert the date column to date type
stops$stop_date <- as.Date(stops$stop_date)

# Drop unrecorded gender
stops <- subset(stops, driver_gender != "")

# Drop unclear stop duration
stops <- subset(stops, stop_duration != "1" & stop_duration != 2)

# Drop unrecorded violation level
stops$violation <- droplevels(stops$violation)

# Make age numeric
stops$driver_age <- as.numeric(stops$driver_age)

# Make some factors boolean
stops$is_arrested <- as.logical(stops$is_arrested)
stops$search_conducted <- as.logical(stops$search_conducted)
stops$drugs_related_stop <- as.logical(stops$drugs_related_stop)

# Order the factors
levels(stops$violation) <- ordered(levels(stops$violation))
```

Column {.sidebar data-width=250}
-----------------------------------------------------------------------

#### Summary

```{r}
# Displays a summary generated by the "summary" output
uiOutput("summary")
```

#### Filters

```{r}
# Filter control for race
selectInput("race", label = "Race:",
            choices = c("All", sort(levels(stops$driver_race))),
            selected="All")

# Filter control for gender
selectInput("gender", label = "Gender:",
            choices = c("All", sort(levels(stops$driver_gender))),
            selected="All")
```

#### Sources and Acknowledgements

Data for this project was made available by the [Stanford Open Policing Project](https://openpolicing.stanford.edu/), and was accessed, in this instance, from [Kaggle](https://www.kaggle.com/faressayah/stanford-open-policing-project). The data consists of records of traffic stops carried out in Rhode Island from January 2005 to December 2015. It is presented here without comment or political agenda.

Should you have any questions/concerns about this project, you can view the code [here](https://github.com/peritract/traffic-dashboard), email the developer at `peritract@hotmail.co.uk`, or confront him on Twitter [here](https://twitter.com/peritract).

```{r}
#Create a reactive dataset
reactive.stops <- reactive({
  if (input$race == "All" && input$gender == "All"){
    stops[,]
  } else {
    if (input$race == "All"){
      stops[which(stops$driver_gender == input$gender), ]
    } else if (input$gender == "All"){
      stops[which(stops$driver_race == input$race), ]
    } else {
      stops[which(stops$driver_race == input$race & stops$driver_gender == input$gender), ]
    }
  }
})
```

```{r}
# Generates a text summary based on selected options
output$summary <- renderUI({
  final_html <- ""
  if (input$race == "All" && input$gender == "All"){
    total <- nrow(stops)
    arrests <- nrow(subset(stops, is_arrested))
    title <- paste0("<h5>All drivers</h5>")
  } else {
    if (input$race == "All"){
      total <- nrow(subset(stops, driver_gender == input$gender))
      arrests <- nrow(subset(stops, (driver_gender == input$gender) & (is_arrested)))
      if (input$gender == "F"){
        title <- paste0("<h5>", "Female ", "drivers</h5>")
      } else {
        title <- paste0("<h5>", "Male ", "drivers</h5>")
      }
    } else if (input$gender == "All"){
     total <- nrow(subset(stops, driver_race == input$race))
     arrests <- nrow(subset(stops, (driver_race == input$race) & (is_arrested)))
      title <- paste0("<h5>", input$race, " drivers</h5>")
    } else {
      total <- nrow(subset(stops, (driver_gender == input$gender) & (driver_race == input$race)))
      arrests <- nrow(subset(stops, (driver_gender == input$gender) & (driver_race == input$race) & (is_arrested)))
      if (input$gender == "F"){
        title <- paste0("<h5>", input$race, " female ", "drivers</h5>")
      } else {
        title <- paste0("<h5>", input$race, " male ", "drivers</h5>")
      }
    }
  }
  
  # Wrap values in html elements/context text
  total.pretty <- paste0("<p>Stop count: ", total, "</p>")
  proportion.pretty <- paste0("<p>Percentage of total stops: ", round((total / nrow(stops))*100,2), "%</p>")
  arrests.pretty <- paste0("<p>Percentage of total arrests: ", round(arrests / nrow(subset(stops, is_arrested))*100,2), "%</p>")
  # Construct and return the final summary
  final_html <- paste0(final_html, title, total.pretty, proportion.pretty, arrests.pretty)
  HTML(final_html)
})
```

Row {data-height=500}
-----------------------------------------------------------------------

### Traffic stops by driver age

```{r}
renderPlot({
ggplot(data=reactive.stops(), aes(x=driver_age, y=..prop..))+
geom_bar(fill="#003271", width=0.5)+
theme(axis.text.x = element_text(angle = 45, hjust=1))+
theme_classic()+
labs(x = "Driver age", y = "Percentage of stops")+
scale_x_continuous(breaks=seq(min(reactive.stops()$driver_age),max(reactive.stops()$driver_age), 10))+
scale_y_continuous(labels = scales::percent_format())
})
```

### Violation types

```{r}
renderPlot({
  
# Get a summarised version of the violation data
plot.data <- as.data.frame(prop.table(table(reactive.stops()$violation)))
plot.data$Freq <- round(plot.data$Freq/1 * 100, 2)

# Plot the violation types
ggplot(data=plot.data, aes(x="", y=Freq, fill=Var1))+
geom_bar(stat="identity")+
geom_text(aes(label = paste0(as.character(Freq), "%")), position = position_stack(vjust=0.5)) +
coord_polar("y", start=0)+
scale_fill_brewer(palette="Blues")+
labs(fill="Violation type")+
theme_void()
})
```

Row
-----------------------------------------------------------------------

### Arrests

```{r}
# Plot the arrested/not arrested counts
renderPlot({
ggplot(data=reactive.stops(), aes(x=is_arrested, y=..prop.., group=1))+
geom_bar(fill="#003271")+
scale_y_continuous(labels = scales::percent_format())+
labs(x = "Arrested", y = "Percentage of stops")+
theme_classic()
})
```

### Stop duration

```{r}
# Plot the stop duration levels
renderPlot({
ggplot(data=reactive.stops(), aes(x=stop_duration, y=..prop.., group=1), c=)+
geom_bar(fill="#003271")+
scale_y_continuous(labels = scales::percent_format())+
labs(x = "Stop duration", y = "Percentage of stops")+
theme_classic()
})
```


